export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_CATEGORIES = "CHANGE_CATEGRIES";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const CHANGE_QUESTIONS = "QUESTIONS";
